name = "osusrealestatepremium"
compatibility_date = "2025-11-28"

[build]
command = "npm run build"
cwd = "./"

[env.production]
routes = [
  { pattern = "properties.erposus.com", zone_name = "erposus.com" },
  { pattern = "properties.erposus.com/*", zone_name = "erposus.com" }
]

[pages]
build_output_directory = "dist"
